#!/usr/bin/env python3
"""Basic example showing how to build, validate, and write a JSON contract."""

from __future__ import annotations

from pathlib import Path
import sys

# NOTE: This keeps the example runnable directly from the repository checkout.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from json_contract_core import (  # noqa: E402
    create_result_contract,
    validate_contract,
    write_json_file,
)


def main() -> int:
    contract = create_result_contract(
        result_type="example_result",
        tool_name="ExampleTool",
        module_name="ExampleModule",
        summary={
            "status": "ok",
            "errors_count": 0,
            "diagnostics_count": 0,
        },
        report_brief={
            "title": "Example result",
            "description": "Minimal contract generated by JsonContractCore.",
        },
        data={
            "items": [],
        },
    )

    validation = validate_contract(contract)

    if not validation.is_valid:
        print("Contract is invalid:")
        for issue in validation.errors:
            print(f"- [{issue.code}] {issue.message}")
        return 1

    output_path = Path("output/example_result.json")
    write_json_file(contract, output_path)

    print(f"Contract status: {validation.status}")
    print(f"JSON written to: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
